### ISSUE TITLE
[env:mega-direct] section of platformio.ini has duplicate build_flags option

### ISSUE THREAD

**Issue by samschloegel** [scottbez1/splitflap#118]
During build, PlatformIO throws the following error from line 64:
```
> Executing task: pio run --environment uno-shift-register <

Error: Invalid '[...]/splitflap/arduino/splitflap/platformio.ini' (project configuration file): 'While reading from '[...]/splitflap/arduino/splitflap/platformio.ini' [line 64]: option 'build_flags' in section 'env:mega-direct' already exists'
The terminal process "pio 'run', '--environment', 'uno-shift-register'" terminated with exit code: 1.
```
I am running an Uno with the uno-shift-register environment, and am not yet familiar enough with Platformio to offer a solution myself, so I have been commenting out line 62 to allow the build to work.

_(My first time submitting an issue on GitHub, apologies in advance if I've stumbled over any conventions here....)_

**Comment by scottbez1** [comment]
Thanks for flagging this @samschloegel! I removed the errant line (as I recall, I had been experimenting with build optimization settings a while ago and I think that was an accidental merge conflict. I don't believe those optimization settings were needed, so I just removed them for now)
