### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DJboyy1** [scottbez1/splitflap#194]
Can i ask some help for the python programs, i tried a lot and still nothing for the SVG file

**Comment by AirmanEpic** [comment]
I'll see what I can do, others can feel free to also take a look, it might take me a while

**Comment by DJboyy1** [comment]
Normaly when you run the python file it will give you a SVG file for the laser cutter but when i try the program it runs but it give no file back.

**Comment by scottbez1** [comment]
Sorry for not responding earlier. The SVG exports for laser-cutting are currently broken in newer versions of python, which could be what you were running into. In any case, I'm closing out some old issues, but please open a new issue with as much debugging context as possible if you still have questions, thanks!
