### ISSUE TITLE
News Headlines from a API?

### ISSUE THREAD

**Issue by someone224466** [scottbez1/splitflap#211]
Hello! I am a bored High-School student and I came across this project and I thought It would be a fun thing to make over the summer and could be pretty easy with the detailed assembly instructions. I wanted to make the split flaps display News headlines from the NYT API. Unfortunately, I have no Idea how I would do this as I am more of a mechanical guy. I found code on this repository that grabs whether info from an API and I tried to figure out what goes into this code and what it produces so I could change it to fetch headlines form the NYT API but I seem to be very unqualified. Im sorry if this is in the wrong spot, I am new to Github.

**Comment by scottbez1** [comment]
Sorry for taking so long to respond. The easiest way (and generally the way I would recommend) would be to fetch the data from the API on the computer the splitflap is connected to. There are python and javascript libraries for controlling the splitflap display over USB in the `software` directory. Going to close this for now, but please reopen a new issue if you have further questions, thanks!
