### ISSUE TITLE
HI sir 

### ISSUE THREAD

**Issue by nicobockko** [scottbez1/splitflap#219]
https://pythonrepo.com/repo/scottbez1-splitflap-python-programming-with-hardware

Hello sir , I'm a beginning Arduino developer. Junsik-Choi in South Korea
I'm impressed with the material you've created.
I was interested to see how to make a Flip Display, but I was informed that the links, such as the .ino, .pro and etc files needed to make it, were not found. I would like to receive the information needed to make it. Please respond if you can.

Thanks you Sir

**Comment by Serdiev** [comment]
Download this git repository and you will find .ino, .pro files.

Seems like the links are broken on that site you linked.

Here for example:
https://github.com/scottbez1/splitflap/blob/master/arduino/splitflap/Splitflap/Splitflap.ino
