### ISSUE TITLE
cards / stickers

### ISSUE THREAD

**Issue by vettorazi** [scottbez1/splitflap#34]
hey guys! where i can find the pdf with the card updated and ready for cut?
i download this pdf in some post here but seems wrong size. (https://github.com/scottbez1/splitflap/files/1976770/Github.Splitflap.Characters.pdf) 
anyone has the pdf of the sticker and the actual size for the pvc card (i am thinking in make with a laser cut in ps)
thanks!!

**Comment by scottbez1** [comment]
The dimension drawing I've used to order custom die-cut flaps was this one: https://github.com/scottbez1/splitflap/blob/master/docs/img/flapAnnotated.png

I also just uploaded the source SVG vector image for that drawing, which I imagine would be more useful for laser-cutting: https://github.com/scottbez1/splitflap/blob/master/docs/img/flapAnnotated.svg

By the way, if you're interested in any kind of adjustments or customization, that SVG was originally exported from the OpenSCAD model by rendering just the `flap()` module: https://github.com/scottbez1/splitflap/blob/3f542af7171e27d1b14e454c6b12f510f014a0dd/3d/splitflap.scad#L375, so if you wanted to adjust any dimensions it's probably best to just update the original model code and render it to SVG again. Plus that way you can double-check that those dimensions work with the rest of the 3d model.
