### ISSUE TITLE
About Sensor of arduino

### ISSUE THREAD

**Issue by whitefang1997** [scottbez1/splitflap#63]
Hi,it's me again.Thank you for your answer last time.
I use magnet+hall effect,but program have some problem.
![1551962106507](https://user-images.githubusercontent.com/47782384/53957118-818c8000-4118-11e9-94dc-7590359f2749.jpg)

Best wishes,
Fang

**Comment by vettorazi** [comment]
install the library: https://github.com/adafruit/Adafruit_NeoPixel

**Comment by scottbez1** [comment]
Closing old issues. Please let me know if you still have questions.
