### ISSUE TITLE
Display different words automatically

### ISSUE THREAD

**Issue by Laserman1974** [scottbez1/splitflap#65]
Hi,

how can I display different words, that I want save in the arduino-code (for example splitflap.ino).
So that I don't need a computer to control the splitflap.

For example display "coffee" wait 5 seconds then display "tea".

How must I change the code exaclty to do this?

I would be very pleased, if someone would be able to answer here.
Perhaps Scott for himself?

Thanks a lot.

*** Deutsch **************************************************************************************

Halli Hallo,

ich möchte hintereinander verschiedene Worte anzeigen, die ich im Arduino-Code speichere. Also will ich das Splitflap-Display ohne Computer betreiben. 

Z.B. Anzeige von "Kaffee" dann 5 Sekunden warten. Dann Anzeige von "Tee".

Es gibt hier doch bestimmt jemanden, für den das ein Klacks ist, also kein Problem darstellt. 

Ich würde mich sehr freuen, wenn hier mal jemand antworten könnte.

**Comment by scottbez1** [comment]
Closing in favor of #35
