### ISSUE TITLE
About Clock

### ISSUE THREAD

**Issue by whitefang1997** [scottbez1/splitflap#69]
I want to make a clock, but I don't know how to rewrite Arduino Program?
I tried to add case ,but it still exists big problem.
What can I do? or something I should know?
Thank you.

Best wishes,
Fang

**Comment by whitebird** [comment]
Where are you exactly gettings stuck? The clock currently is focused on being a full text display and is not easily adapted to display only numbers. More info on that here: https://github.com/scottbez1/splitflap/issues/62

**Comment by scottbez1** [comment]
Cleaning up old issues. Apologies for not answering this one earlier. If you still have questions, please comment here or open a new issue, ideally with some sample code or a description of what you've tried so far that hasn't worked. Thanks!
