### ISSUE TITLE
Ordered PCB's on tindie, didn't receive all components

### ISSUE THREAD

**Issue by whitebird** [scottbez1/splitflap#73]
Hello @scottbez1 ,

On Tindie I ordered the controller PCB's, flaps and hall effect sensor board. I received all but the hall effect sensor board. Can you maybe check the order? I tried messaging you on Tindie; but haven't received a response yet.

Thank you in advance!

**Comment by scottbez1** [comment]
Really sorry about that. I must have missed them in the order. I'll ship some out tomorrow!

**Comment by scottbez1** [comment]
These are in the mail!
