### ISSUE TITLE
Using 3.0mm MDF (Ponoko no longer carries 3.2mm)

### ISSUE THREAD

**Issue by ericyeargan** [scottbez1/splitflap#76]
The OpenSCAD script and ordering guide specify 3.2mm MDF for the laster-cut parts. Unfortunately, it looks like Ponoko no longer carries 3.2mm. In some commentary in the ordering guide @scottbez1 suggests that it's possible that the material was always 3.0mm and that the Ponoko was just listing it incorrectly as 3.2mm.

So, I tried ordering a parts using 3.0mm MDF with the latest release but things don't fit quite right - there are visible gaps in the slots and a good amount of give when you lightly twist the spindle. (FYI, when measuring the material thickness with calipers, it's right around 2.99mm).

I've also tried modifying the OpenSCAD to change the material width to 3.0mm and update the kerf. I ordered parts with that updated pattern and things fit better although there's very little/no clearance between the spindle and sides. I had to reduce the top spindle speed to keep the motor from stalling - I suspect because the spindle is rubbing slightly against the sides. You can view the commit with the OpenSCAD change [here](https://github.com/ericyeargan/splitflap/commit/0d5985a39a45576651774b16db48451103f24ab1).

Curious if anyone else has dealt with this. My ultimate goal is to build 12 modules. Right now, I'm trying to decide wether to mess with the 3.0mm SCAD to increase the spindle clearance or to just live with a loose fit on the 3.2mm SCAD (maybe through some liberal CA glue application).

P.S. Despite these issues, I've been having a blast with this project. Thanks @scottbez1 and all of the contributors!

**Comment by whitebird** [comment]
Ah, weird, I cut out from 3mm myself and it fit very well together. Maybe there is a kerf difference between my lasercutter, a trotec speedy 300, and the one ponoko uses.

**Comment by ericyeargan** [comment]
Thanks @whitebird. I should note that I haven't actually built the entire module with the unmodified pattern. Maybe I'll find that it works just fine once everything's bolted together.

**Comment by ericyeargan** [comment]
The Ponoko 3mm ended up working pretty well. I did have to apply some glue to the spindle joints. Otherwise, it would get out of wack if you applied even a little torsion to the sides. The only other issue is that the tabs stick out very slightly from the front panel/face. That probably wouldn't be an issue for most people but I'm thinking about covering the fronts in a wood veneer so I need it to be fairly flat. It's easy to sand those down though before attaching the front panel.

I'll leave this issue open in case @scottbez1 wants to update the ordering instructions. Otherwise, feel free to close.
