### ISSUE TITLE
The first Aliexpress link for the 28byj-48 5V motor on the wiki page is broken.

### ISSUE THREAD

**Issue by johnmlee101** [scottbez1/splitflap#99]
https://github.com/scottbez1/splitflap/wiki/Motor-info

Links to http://www.aliexpress.com/item/Smart-Electronics-28BYJ-48-5V-4-Phase-DC-Gear-Stepper-Motor-ULN2003-Driver-Board-for-Arduino/32314913056.html which cannot be found.

Found a few alternatives here: https://www.aliexpress.com/w/wholesale-stepper-motor-28byj48.html
But not sure if any follow the similar spec. Otherwise I'd recommend crossing out the existing link.

**Comment by scottbez1** [comment]
Thanks for the heads up (and sorry for taking so long to respond)! I've updated the wiki with a link to the most recent recommendations on the [Ordering Splitflap](https://paper.dropbox.com/doc/Ordering-Splitflap-v0.5v0.6--BBI3CicsM~NHdb9FflcqYGKtAg-iCwwMo0hRkkAlwdutccWf) document -- currently https://www.aliexpress.com/item/32860037285.html is the recommended source (but as always when ordering from AliExpress, you never know exactly what you'll get, and you may get something different even if you reorder from the same seller...)
